# Generated by Django 3.2.12 on 2022-04-10 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=3)),
                ('chapters', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('verses', models.IntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.book')),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('text', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.book')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.verse')),
            ],
        ),
        migrations.CreateModel(
            name='Interlinear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=200)),
                ('use', models.CharField(max_length=200)),
                ('classification', models.CharField(max_length=100)),
                ('transcription', models.CharField(max_length=200)),
                ('pronounce', models.CharField(max_length=200)),
                ('spelling', models.CharField(max_length=200)),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.verse')),
            ],
        ),
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.verse')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.version'),
        ),
    ]
