# Generated by Django 3.2.12 on 2022-06-01 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idiom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=10)),
                ('default', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='version',
        ),
        migrations.RemoveField(
            model_name='dictionary',
            name='verse',
        ),
        migrations.RemoveField(
            model_name='interlinear',
            name='verse',
        ),
        migrations.RemoveField(
            model_name='verse',
            name='text',
        ),
        migrations.AddField(
            model_name='interlinear',
            name='strong',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reference',
            name='reference',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reference_fk', to='webapp.verse'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verse',
            name='references',
            field=models.ManyToManyField(blank=True, null=True, related_name='_webapp_verse_references_+', through='webapp.Reference', to='webapp.Verse'),
        ),
        migrations.AddField(
            model_name='version',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='abbreviation',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='reference',
            name='verse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verse_fk', to='webapp.verse'),
        ),
        migrations.AlterField(
            model_name='version',
            name='abbreviation',
            field=models.CharField(max_length=5),
        ),
        migrations.CreateModel(
            name='VerseVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.verse')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.version')),
            ],
        ),
        migrations.CreateModel(
            name='VerseInterlinear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interlinear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.interlinear')),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.verse')),
            ],
        ),
        migrations.CreateModel(
            name='VerseDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dictionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.dictionary')),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.verse')),
            ],
        ),
        migrations.CreateModel(
            name='BookVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.book')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.version')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='versions',
            field=models.ManyToManyField(through='webapp.BookVersion', to='webapp.Version'),
        ),
        migrations.AddField(
            model_name='verse',
            name='dictionaries',
            field=models.ManyToManyField(blank=True, null=True, through='webapp.VerseDictionary', to='webapp.Dictionary'),
        ),
        migrations.AddField(
            model_name='verse',
            name='intelinears',
            field=models.ManyToManyField(blank=True, null=True, through='webapp.VerseInterlinear', to='webapp.Interlinear'),
        ),
        migrations.AddField(
            model_name='verse',
            name='versions',
            field=models.ManyToManyField(through='webapp.VerseVersion', to='webapp.Version'),
        ),
        migrations.AddField(
            model_name='version',
            name='idiom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.idiom'),
            preserve_default=False,
        ),
    ]
