# Generated by Django 3.2.12 on 2022-06-24 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20220624_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reference',
            old_name='chapters',
            new_name='chapter',
        ),
    ]
