# Generated by Django 3.2.12 on 2022-06-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_rename_chapters_reference_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='verse',
            field=models.CharField(max_length=100),
        ),
    ]
