# Generated by Django 3.2.12 on 2022-06-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_reference_verse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interlinear',
            name='origin',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='interlinear',
            name='use',
            field=models.TextField(),
        ),
    ]
