# Generated by Django 3.2.12 on 2022-06-30 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_alter_interlinear_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interlinear',
            name='definition',
            field=models.TextField(),
        ),
    ]
