# Generated by Django 4.0.2 on 2022-12-29 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_alter_interlinear_definition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verse',
            name='dictionaries',
            field=models.ManyToManyField(blank=True, through='webapp.VerseDictionary', to='webapp.Dictionary'),
        ),
        migrations.AlterField(
            model_name='verse',
            name='intelinears',
            field=models.ManyToManyField(blank=True, through='webapp.VerseInterlinear', to='webapp.Interlinear'),
        ),
    ]
