# Generated by Django 4.0.2 on 2023-04-20 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_remove_order_checkout_url_remove_order_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status_detail',
        ),
    ]
