# Generated by Django 4.0.2 on 2023-04-20 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_remove_order_status_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_id',
        ),
    ]
